[package]
name = "rust_sqlite_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
execute_evcxr = { version = "0.1.1"}
rustyline = "17.0.2"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.0", features = ["full"] }

